channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - bcrypt==3.2.0
  - boto3==1.24.28
  - defusedxml==0.7.1
  - dill==0.3.6
  - fsspec==2023.3.0
  - lz4==4.3.2
  - numpy==1.24.3
  - packaging==23.0
  - pandas==1.5.3
  - pathlib==1.0.1
  - protobuf==4.24.3
  - pyopenssl==23.2.0
  - python-snappy==0.6.1
  - requests==2.31.0
  - scipy==1.10.1
  - tblib==1.7.0
  - tensorflow-intel==2.13.0
  - tensorflow==2.13.0
  - zstandard==0.19.0
name: mlflow-env
